name: Unit test

on:
  push:
  pull_request:
    branches: [ "main", "int" ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
