name: Unit test

on:
  push:
  pull_request:
    branches: [ "main", "int" ]

jobs:

  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

    - name: Set up Go
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
